export const FETCH_DATA_REQUESTED = 'FETCH_DATA_REQUESTED';
export const FETCH_DATA_SUCCESSFUL = 'FETCH_DATA_SUCCESSFUL';
export const FETCH_DATA_DEBOUNCED = 'FETCH_DATA_DEBOUNCED';
export const FILTER_GENDER = 'FILTER_GENDER';
export const APPLY_FILTER_GENDER = 'APPLY_FILTER_GENDER';
export const REMOVE_FILTER_GENDER = 'REMOVE_FILTER_GENDER';
export const APPLY_REMOVE_FILTER_GENDER = 'APPLY_REMOVE_FILTER_GENDER';
